name: Update films.json

permissions:
  contents: write

on:
  # schedule:
   # - cron: '*/5 * * * *'  # Toutes les 5 minutes
  workflow_dispatch:         # Permet de lancer manuellement

jobs:
  update-films:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du d√©p√¥t
        uses: actions/checkout@v3

      - name: Configurer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installer les d√©pendances
        run: pip install -r requirements.txt

      - name: Ex√©cuter le script
        run: python update_films.py
      
      - name: Commit et push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add films.json checksumfilms.json || true
          git diff --cached --quiet || git commit -m "üîÑ Mise √† jour automatique de films.json"
          git push
